/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPages;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author B N Bhattacharya
 */
public class ExpertKnow extends javax.swing.JFrame {
GridBagLayout layout = new GridBagLayout();
ExpertKWall page1;
RobotLocomotion page2;
RobotManipulation page3;
RobotVision page4;
RobotTouch  page5;
RobotArtificialEmotions page6;
RobotHumanInteraction  page7;
DynamicsKinematics   page8;
   /**
     * Creates new form BasicKnow
     */
    public ExpertKnow() {
 this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        this.setResizable(true);
        this.setVisible(true);
                initComponents();
                Toolkit tk=Toolkit.getDefaultToolkit();
                int xsize= (int) tk.getScreenSize().getWidth();
                int ysize= (int) tk.getScreenSize().getHeight();
                this.setSize(xsize ,ysize);   
                
                page1 = new ExpertKWall();
                page2 = new RobotLocomotion();
                page3 = new RobotManipulation();
                page4 = new RobotVision();
                page5 = new RobotTouch();
                page6 = new RobotArtificialEmotions();
                page7 = new RobotHumanInteraction();
                page8 = new DynamicsKinematics();
        jPanel3.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        jPanel3.add(page1,c);
         page1.setVisible(true);
        c.gridx = 0;
        c.gridy = 0;
        jPanel3.add(page2,c);
        page2.setVisible(false);
        c.gridx = 0;
        c.gridy = 0;
        jPanel3.add(page3,c);
        page3.setVisible(false);
        c.gridx = 0;
        c.gridy = 0;
        jPanel3.add(page4,c);
        page4.setVisible(false);
        c.gridx = 0;
        c.gridy = 0;
        jPanel3.add(page5,c);
        page5.setVisible(false);
        c.gridx = 0;
        c.gridy = 0;
        jPanel3.add(page6,c);
        page6.setVisible(false);
        c.gridx = 0;
        c.gridy = 0;
        jPanel3.add(page7,c);
        page7.setVisible(false);
         c.gridx = 0;
        c.gridy = 0;
        jPanel3.add(page8,c);
        page8.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        topic1 = new javax.swing.JMenuItem();
        topic2 = new javax.swing.JMenuItem();
        topic3 = new javax.swing.JMenuItem();
        topic4 = new javax.swing.JMenuItem();
        topic5 = new javax.swing.JMenuItem();
        topic6 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        back = new javax.swing.JMenuItem();
        close = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EXPERTISE Level Material | MAGNUS Robotical Technologies  @Arpan");

        jInternalFrame1.setTitle("BASIC Level Material  |  RoboKnowledge  | MAGNUS Robotical Technologies  @Arpan");
        jInternalFrame1.setFrameIcon(null);
        jInternalFrame1.setVisible(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());
        jInternalFrame1.getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(51, 204, 0));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        home.setForeground(new java.awt.Color(102, 0, 102));
        home.setText("HOME");
        home.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jMenuBar1.add(home);

        jMenu2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setForeground(new java.awt.Color(0, 0, 255));
        jMenu2.setText("Reading Materials");
        jMenu2.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N

        topic1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.SHIFT_MASK));
        topic1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        topic1.setText("Locomotion");
        topic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topic1ActionPerformed(evt);
            }
        });
        jMenu2.add(topic1);

        topic2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.SHIFT_MASK));
        topic2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        topic2.setText("Manipulation");
        topic2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topic2ActionPerformed(evt);
            }
        });
        jMenu2.add(topic2);

        topic3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.SHIFT_MASK));
        topic3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        topic3.setText("Vision");
        topic3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topic3ActionPerformed(evt);
            }
        });
        jMenu2.add(topic3);

        topic4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.SHIFT_MASK));
        topic4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        topic4.setText("Touch");
        topic4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topic4ActionPerformed(evt);
            }
        });
        jMenu2.add(topic4);

        topic5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.SHIFT_MASK));
        topic5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        topic5.setText("Artificial Emotions (Short Note)");
        topic5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topic5ActionPerformed(evt);
            }
        });
        jMenu2.add(topic5);

        topic6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.SHIFT_MASK));
        topic6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        topic6.setText("Human Robot Interaction");
        topic6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topic6ActionPerformed(evt);
            }
        });
        jMenu2.add(topic6);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_7, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jMenuItem1.setText("Dynamics and kinematics");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu3.setForeground(new java.awt.Color(153, 0, 0));
        jMenu3.setText("Basic Function");
        jMenu3.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        back.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_UP, java.awt.event.InputEvent.ALT_MASK));
        back.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jMenu3.add(back);

        close.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        close.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        close.setText("Close Magnus");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jMenu3.add(close);

        jMenuBar1.add(jMenu3);

        jInternalFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 1374, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
       
// TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
   page1.setVisible(true);
page2.setVisible(false);
page3.setVisible(false);
page4.setVisible(false);
page5.setVisible(false);
page6.setVisible(false);
page7.setVisible(false);
page8.setVisible(false);
    // TODO add your handling code here:
    }//GEN-LAST:event_homeMouseClicked

    private void topic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topic1ActionPerformed
page2.setVisible(true);
page1.setVisible(false);
page3.setVisible(false);
page4.setVisible(false);
page5.setVisible(false);
page6.setVisible(false);
page7.setVisible(false);
page8.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_topic1ActionPerformed

    private void topic2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topic2ActionPerformed
  page3.setVisible(true);
  page1.setVisible(false);
  page2.setVisible(false);
  page4.setVisible(false);
page5.setVisible(false);
page6.setVisible(false);
page7.setVisible(false);
 page8.setVisible(false);


        
// TODO add your handling code here:
    }//GEN-LAST:event_topic2ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
ImageIcon icon= new ImageIcon("src/AppPages/MessageLogo.png");
        int a= JOptionPane.showConfirmDialog(this, "Do you really want to leave this Page and go back to RoboKnowledge?", "Are You Sure....", JOptionPane.YES_NO_OPTION , JOptionPane.PLAIN_MESSAGE, icon);
if (a==0)
{
        new RoboKnowledge().setVisible(true);
this.setVisible(false);
}       
// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
System.exit(0);       
        
// TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    private void topic3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topic3ActionPerformed
   page3.setVisible(false);
  page1.setVisible(false);
  page2.setVisible(false);
  page4.setVisible(true);
  page5.setVisible(false);
  page6.setVisible(false);
  page7.setVisible(false);
   page8.setVisible(false);

  // TODO add your handling code here:
    }//GEN-LAST:event_topic3ActionPerformed

    private void topic4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topic4ActionPerformed
page3.setVisible(false);
  page1.setVisible(false);
  page2.setVisible(false);
  page4.setVisible(false);
  page5.setVisible(true);
  page6.setVisible(false);
  page7.setVisible(false);
   page8.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_topic4ActionPerformed

    private void topic5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topic5ActionPerformed
page3.setVisible(false);
  page1.setVisible(false);
  page2.setVisible(false);
  page4.setVisible(false);
  page5.setVisible(false);
  page6.setVisible(true);  
  page7.setVisible(false);
 page8.setVisible(false);
        
// TODO add your handling code here:
    }//GEN-LAST:event_topic5ActionPerformed

    private void topic6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topic6ActionPerformed
page7.setVisible(true);
page3.setVisible(false);
  page1.setVisible(false);
  page2.setVisible(false);
  page4.setVisible(false);
  page5.setVisible(false);
  page6.setVisible(false);  
   page8.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_topic6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
 page8.setVisible(true); 
 page7.setVisible(false);
page3.setVisible(false);
  page1.setVisible(false);
  page2.setVisible(false);
  page4.setVisible(false);
  page5.setVisible(false);
  page6.setVisible(false); 
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExpertKnow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExpertKnow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExpertKnow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExpertKnow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExpertKnow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem back;
    private javax.swing.JMenuItem close;
    private javax.swing.JMenu home;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem topic1;
    private javax.swing.JMenuItem topic2;
    private javax.swing.JMenuItem topic3;
    private javax.swing.JMenuItem topic4;
    private javax.swing.JMenuItem topic5;
    private javax.swing.JMenuItem topic6;
    // End of variables declaration//GEN-END:variables
}
