/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPages;

import static AppPages.SignUp.jTextField1;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author B N Bhattacharya
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        this.setUndecorated(false);
        this.setAlwaysOnTop(true);
        this.setResizable(true);
        this.setVisible(true);
                initComponents();
                Toolkit tk=Toolkit.getDefaultToolkit();
                int xsize= (int) tk.getScreenSize().getWidth();
                int ysize= (int) tk.getScreenSize().getHeight();
                this.setSize(xsize ,ysize);
      jButton4.setVisible(false);
    }
    int attempt=1;
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        BASE = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        cost = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN | MAGNUS Robotical Technologies  @Arpan");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPages/EXIT.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1290, 10, 60, 60);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                             MAGNUS   LOGIN   ");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.red, java.awt.Color.red));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 20, 1030, 90);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 44)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USER ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 500, 340, 54);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 44)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSWORD");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 610, 300, 50);

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(420, 500, 500, 70);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButton1.setText("PROCEED");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1050, 580, 290, 60);

        jPasswordField1.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(420, 600, 500, 70);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 0));
        jButton2.setText("I  Don't  have  account");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1050, 500, 290, 60);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("I Forgot UserID");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1050, 160, 280, 50);

        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("Enter Phone Number OR Email ID");
        jTextField2.setEnabled(false);
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField2MousePressed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(1090, 220, 200, 30);

        jRadioButton1.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Search By Phone Number");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(1100, 260, 180, 23);

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 255, 0));
        jButton4.setText("Change My Password");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1050, 330, 280, 50);

        BASE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPages/Login.jpg"))); // NOI18N
        getContentPane().add(BASE);
        BASE.setBounds(0, 0, 1366, 730);

        name.setText("jTextField2");
        getContentPane().add(name);
        name.setBounds(300, 130, 59, 20);

        type.setText("jTextField3");
        getContentPane().add(type);
        type.setBounds(290, 190, 59, 20);

        cost.setText("jTextField4");
        getContentPane().add(cost);
        cost.setBounds(320, 240, 59, 20);

        jLabel10.setText("jLabel1");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(1010, 350, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        //deleting record from CART while closing app
        try
{
    Class.forName("java.sql.DriverManager");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost:3306","root","root");
    Statement stmt = (Statement) con.createStatement();
    String query2 = "DELETE FROM Cart;";
    String query1 = "USE Magnus;";
    stmt.executeUpdate(query1);
    stmt.executeUpdate(query2);
}
 catch(Exception e)
 {
     JOptionPane.showMessageDialog(this, e.getMessage());
 }    
        
        this.setVisible(false);     // TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            //checking password
        String Userid = jTextField1.getText();
        String Password = jPasswordField1.getText();
        String PassW="", Cname="";
                try
{
    Class.forName("java.sql.DriverManager");
    Connection con = (Connection)
    DriverManager.getConnection("jdbc:mysql://localhost:3306/magnus","root","root");
    Statement stmt = (Statement) con.createStatement();
    String query1 = "Use Magnus;";
    String query2 ="SELECT Cname,Password FROM Customer WHERE U_Id='"+Userid+"';";
    stmt.executeUpdate(query1);
    ResultSet rs =stmt.executeQuery(query2);
    if(rs.next())                                         //is username present
    {
     PassW=rs.getString("Password");
     Cname = rs.getString("Cname");     
       
         if(Password.equals(PassW))                           //if password maches with DB
            {
                      try
                {
                    Class.forName("java.sql.DriverManager");
                    //Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/magnus","root","root");
                    //Statement stmt = (Statement) con.createStatement();
                    String query3 = "Use Magnus;";
                    String query4 ="DELETE FROM Cart;";
                    String query5 ="INSERT INTO Cart (U_Id,Date) VALUES ('"+Userid+"',CURDATE());";
                    stmt.executeUpdate(query3);
                    stmt.executeUpdate(query4);
                    stmt.executeUpdate(query5);

                    JOptionPane.showMessageDialog(this,"Welcome "+Cname);
                    this.setVisible(false);
                }
                        catch (Exception e)
                        {
                            JOptionPane.showMessageDialog(this, e.getMessage());
                        }
                
            }
         else if((attempt==3) && (!(Password.equals(PassW))))
                 {
                     JOptionPane.showMessageDialog(this,"Maximum Attempts Exceeded!\n Good Luck Next Time!");
                     int a = JOptionPane.showConfirmDialog(this, "Do you want to Change your Password?","MAGNUS Passwords!!", JOptionPane.YES_NO_OPTION);
                     if(a==0)
                     {
                         JOptionPane.showMessageDialog(this,"You can change your password by pressing CHANGE MY PASSWORD Button");
                         jButton4.setVisible(true);
                     }
                     else if(a==1)
                     {
                     this.setVisible(false);    
                     }
                }
         else if (jPasswordField1.getText().equals(""))       //empty field
         {
           JOptionPane.showMessageDialog(this,"Password Field Blank! \nEnter Password!");    
         }         
         else
            {
               JOptionPane.showMessageDialog(this,"Incorrect Password!\nAttempt:"+attempt+"/3");
               attempt++;
               jPasswordField1.setText("");
            }    
    }
    else
    {
        JOptionPane.showMessageDialog(this,"Account Missing!");
    }
    
}
                catch (Exception e)
                {
                    JOptionPane.showMessageDialog(this,e.getMessage());
                }
        
                  
  
            
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new SignUp().setVisible(true);
this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
jTextField2.setEnabled(true);
//TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
if(jTextField2.getText().isEmpty())
{
    JOptionPane.showMessageDialog(this, "Enter a phone number to search UserID!");
}
else
{
        String Ph = jTextField2.getText();
try
{
    Class.forName("java.sql.DriverManager");
    Connection con = (Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306","root","root");
    Statement stmt = (Statement) con.createStatement();
    String query2 = "Use Magnus;";
        stmt.executeUpdate(query2);
    String query1 = "SELECT U_Id FROM Customer Where PhoneNo LIKE '%"+Ph+"';";
    ResultSet rs = stmt.executeQuery(query1);
    
    if(rs.next())
    {
        jTextField1.setText(rs.getString("U_Id"));
    }
    else
    {
        JOptionPane.showMessageDialog(this,"Data Not Present in MAGNUS!");
    }
}
catch (Exception e)
{
    JOptionPane.showMessageDialog(this,e.getMessage());
} 
}
 // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
jTextField2.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2MouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String userid = jTextField1.getText();
String NPass = JOptionPane.showInputDialog(this, "ENTER NEW PASSWORD!");
String RePass = JOptionPane.showInputDialog(this, "RE-ENTER PASSWORD!");
if(NPass.equals(RePass))
{
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306","root","root");
            Statement stmt = (Statement) con.createStatement();
            String query1 = "Use MAGNUS;";

             String query2 = "UPDATE Customer SET Password ='"+RePass+"' WHERE U_Id = '"+userid+"';";
            stmt.executeUpdate(query1);
            stmt.executeUpdate(query2);
          JOptionPane.showMessageDialog(this, "Password Changed!");
        }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
}
else
{
    JOptionPane.showMessageDialog(this, "Password not matching after Re-Entering!");
}
   
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MousePressed
       jTextField2.setText(""); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BASE;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JTextField cost;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    public static javax.swing.JTextField name;
    public static javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
